### PR TITLE
Additional features

### PR DESCRIPTION
**Pull request by GenieTim**
This PR adds three more features and fixes one small typo. Thank you very much for this project, I like the design and idea very much!

### CODE REVIEW

**Comment by rosswintle** [comment]
Hmm... this is my first time accepting contributions like this. So sorry if this is a stupid question:

I can't push some tweaks back to the contribution. Have you got the "Allow edits from maintainers" turned off?

See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thanks

**Comment by GenieTim** [comment]
@rosswintle I am sorry, it seems that checkbox does not exist as I accidentally seem to have forked the repo as an organisation.

See https://github.com/isaacs/github/issues/1681 and https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/8 and https://github.com/whatwg/html/pull/3881#issuecomment-668467097 as to why I think this is the case.

Would it help if I gave you maintainer access to my fork? Or shall I push and PR again from a private fork?

**Comment by rosswintle** [comment]
Don't worry - I'll fix my end somehow. Thanks!

**Comment by rosswintle** [comment]
Will merge this and then add on #17 (if you want to see how I modified it).

Key things:
 - Backticks didn't work in descriptions (this is fixed in #17)
 - Ordering of items (I'm putting newest at the top)
 - Some tweaks to the text and resoruce links.

Thanks for getting this researched and added!

**Pull request merged**
