### PR TITLE
feat: add PHP 8.2 features

### PR DESCRIPTION
**Pull request by owenvoke**
I was thinking of starting to add PHP 8.2 features, and have this as a long-running draft PR. However, I'm happy to close this and re-open it after the feature freeze for 8.2 👍🏻

### CODE REVIEW

**Comment by rosswintle** [comment]
Thanks again, Owen. I don't see why we shouldn't start to add this data in.

I'm thinking of adding "Show changes in..." filters for each version. So having a summary here of what's coming in PHP8.2 would be good.

I'll maybe implement those filters and then we can merge this in (but keep it open for additions).

How does that sound?

At some point this is going to be more than a single HTML file... 😬

**Comment by owenvoke** [comment]
Sounds good to me. 🥳

**Comment by rosswintle** [comment]
I've added some stuff and I think this is up to date with proposed 8.2 changes now (after reading through https://stitcher.io/blog/new-in-php-82)

I'm going to merge it and then try to keep it up to date. Thanks so much! 🙌

**Comment by owenvoke** [comment]
Woo! Yeah, I wasn't sure which things to include as some of it I couldn't find good resources for.

**Pull request merged**
