### PR TITLE
Add typed arguments

### PR DESCRIPTION
**Pull request by snoop0x7b**
I added typed arguments, which were a new feature in PHP7

### CODE REVIEW

**Comment by rosswintle** [comment]
Thanks for this. I'm loving the contributions. 🙌 

I can see that PHP 7.0 added scalar type hints (as opposed to class type hints) and return types.

But I can't see it doucmented anywhere that typed function/method arguments were added. Do you have a reference you can point me at to show that this was added in PHP 7.0 please?

**Comment by snoop0x7b** [comment]
I was having a difficult time finding a specific reference to when classtype hints were added, so I wrote this little bit of code: 

`<?php

function myFunction(string $myParam) {
	echo $myParam;
}


function myFunction2(MyClass $myClass) {
	echo $myClass->name;
}
class MyClass {
	public $name;
}



myFunction("Blah");

$myItem = new MyClass();

$myItem->name = 'blahblah';

myFunction2($myItem);
`

Which is runnable in PHP >= 7.0. Although that uses both scalar hints and class hints. 

Removing the scalar hint, to end up with 

`<?php
/*
function myFunction(string $myParam) {
        echo $myParam;
}

 */

function myFunction2(MyClass $myClass) {
        echo $myClass->name;
}
class MyClass {
        public $name;
}



//$myFunction("Blah");

$myItem = new MyClass();

$myItem->name = 'blahblah';

myFunction2($myItem);
`

That actually works with PHP 5. 

So this could probably be fixed to have "scalar type"  (7) and "class type" (5)

**Comment by snoop0x7b** [comment]
Reference-wise. https://www.php.net/ChangeLog-5.php 5.1 added array type hinting and nullable type hinting. 5.0 added type hinting. https://www.php.net/ChangeLog-7.php 7.0 added scalar type.

**Comment by rosswintle** [comment]
Oh. Why'd you close it? I was updating it and wanted to keep you as a contributor!

**Comment by rosswintle** [comment]
Leave it with me. I do appreciate the contribution.

I don't want to go back to v5.0. That would involve a whole lot more work.

But I'll document more of this type stuff, merge our work together, and get you added as a contributor. You did some good research here! Thanks.

**Comment by snoop0x7b** [comment]
Oh, I closed it because I thought I was wrong, but yeah, I can leave it with you.

**Comment by rosswintle** [comment]
Oh, GitHub confused me. This will be resolved by #11

**Pull request closed without merging**
